# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'snacksApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for snacksApp

  target 'snacksApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'snacksAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'GoogleSignIn', '~> 4.4.0'

end


